apiVersion: v1
kind: Pod
metadata:
  name: server-b
  labels:
    server: "http"
spec:
  containers:
    - name: front-end
      image: beppev/server-b:latest 
      ports:
        - containerPort: 5000
