apiVersion: v1
kind: Pod
metadata:
  name: server-a
  labels:
    server: "http"
    expose: "true"
spec:
  containers:
    - name: front-end
      image: IMAGE-A
      ports:
        - containerPort: 5000

