---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-project-1
  labels:
    istio-injection: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-a
  namespace: istio-project-1
spec:
  replicas: 1
  selector:
    matchLabels:
      server: "http"
      app: "ja"
      expose: "true"
  template:
    metadata:
      labels:
        server: "http"
        app: "ja"
        expose: "true"
        backend: "true"
    spec:
      containers:
        - name: front-end
          image: beppev/server-a:latest
          ports:
            - containerPort: 5000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-b
  namespace: istio-project-1
spec:
  replicas: 1
  selector:
    matchLabels:
      server: "http"
      app: "ja"
      version: v1
  template:
    metadata:
      labels:
        server: "http"
        app: "ja"
        version: v1
    spec:
      containers:
        - name: front-end
          image: beppev/server-b:latest
          ports:
            - containerPort: 6000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-c
  namespace: istio-project-1
spec:
  replicas: 1
  selector:
    matchLabels:
      server: "http"
      app: "ja"
      version: v2
  template:
    metadata:
      labels:
        server: "http"
        app: "ja"
        version: v2
    spec:
      containers:
        - name: front-end
          image: beppev/server-c:latest
          ports:
            - containerPort: 6000
---
apiVersion: v1
kind: Service
metadata:
  name: server-b-c-service
  namespace: istio-project-1
spec:
  selector:
    backend: "true"
  ports:
    - name: http
      protocol: TCP
      port: 6000

---
kind: Service
apiVersion: v1
metadata:
  name: expose-server
  namespace: istio-project-1
spec:
  type: NodePort
  selector:
    expose: "true"
  ports:
    - name: http
      protocol: TCP
      targetPort: 5000
      port: 5000
      nodePort: 30036
---
kind: Service
apiVersion: v1
metadata:
  name: example-loadbalancer
  namespace: istio-project-1
spec:
    selector:
        expose: "true"
    ports:
        - name: http
          protocol: TCP
          targetPort: 5000
          port: 80
    type: LoadBalancer
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: server-check-destination
  namespace: istio-project-1
spec:
  host: server-b-c-service
  subsets:
  - name: v1
    labels:
      version: v1
  - name: v2
    labels:
      version: v2
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: server-check-gateway
  namespace: istio-project-1
spec:
  selector:
    expose: "true"
  servers:
    - port:
        number: 6000
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: v1
kind: Service
metadata:
  name: server-check
  namespace: istio-project-1
spec:
  selector:
    expose: "true"
    version: v1
    version: v2
  ports:
    - name: http
      protocol: TCP
      targetPort: 6000
      port: 6000
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: server-check-service
  namespace: istio-project-1
spec:
  hosts:
    - "*"
  gateways:
    - server-check-gateway
  tcp:
  - match:
    - port: 6000
    route:
    - destination:
        host: server-b-c-service
        port:
          number: 6000
        subset: v1
      weight: 50
    - destination:
        host: server-b-c-service
        port:
          number: 6000
        subset: v2
      weight: 50
