---
apiVersion: v1
kind: Namespace
metadata:
  name: getting-started

---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: getting-started-listener
  namespace: getting-started
spec:
  serviceAccountName: tekton-triggers-admin
  triggers:
    - bindings:
      - name: getting-started-pipelinebinding
      template:
        name: getting-started-triggertemplate