---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-master
  namespace: tekton-pipeline-istio-project-1
spec:
  type: git
  params:
    - name: revision
      value: master
    - name: url
      value: git://github.com/beppevanrolleghem/cicdTest
---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: git-experimental
  namespace: tekton-pipeline-istio-project-1
spec:
  type: git
  params:
    - name: revision
      value: experimental
    - name: url
      value: git://github.com/beppevanrolleghem/cicdTest