---
apiVersion: tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: github-event-listener
spec:
  serviceAccountName: service-acc
  triggers:
  - binding:
      name: github-trigger-binding
    template:
      name: github-trigger-template