---
apiVersion: tekton.dev/v1alpha1
kind: Task
metadata:
  name: build-and-push
  namespace: tekton-pipeline-istio-project-1
spec:
  inputs:
    resources:
      - name: git-source
        type: git
    params:
      - name: context
        description: The path to the build context, used by Kaniko - within the workspace
        default: .
      - name: image-name
        description: dockerhub url
      - name: version
        description: image-version (for instance latest or beta)
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor
      env:
        - name: "DOCKER_CONFIG"
          value: "/tekton/home/.docker/"
      command:
        - /kaniko/executor
      args:
        - "--dockerfile=$(inputs.resources.git-source.path)/$(inputs.params.context)/dockerfile"
        - "--destination=beppev/$(inputs.params.image-name):$(inputs.params.version)"
        - "--context=$(inputs.resources.git-source.path)/$(inputs.params.context)/"