apiVersion: tekton.dev/v1alpha1
kind: PipelineRun
metadata:
  name: application-pipeline-run
spec:
  serviceAccountName: tutorial-service
  pipelineRef:
    name: application-pipeline
  resources:
    - name: git-source
      resourceRef:
        name: git
  params:
    - name: pathToYamlFile
      value: "deploy.yaml"
    - name: pathToContext
      value: "."
    - name: imageUrl-a
      value: "gs://BUCKETNAME/server-a"
    - name: imageTag-a
      value: "release"
    - name: pathToContext-a
      value: "./serverA"
    - name: imageUrl-b
      value: "gs://BUCKETNAME/server-b"
    - name: imageTag-b
      value: "release"
    - name: pathToContext-b
      value: "./serverB"

